/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.fynrir.kek.terraincontrolgui.swing;

/**
 *
 * @author cbg-fynrir
 */
public class terraincontrol_ini_frame extends javax.swing.JFrame {
    Operations operations = new Operations();
    /**
     * Creates new form terraincontrol_ini_frame
     */
    public terraincontrol_ini_frame() {
        initComponents();
        System.out.println(operations.getTerrainControlINISettings());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbboxSettingsMode = new javax.swing.JComboBox<>();
        cmbboxLogLevel = new javax.swing.JComboBox<>();
        cmbboxBiomeExtension = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblMessageSettingsModeCMBBOX = new javax.swing.JLabel();
        lblMessageLogLevelCMBBOX = new javax.swing.JLabel();
        lblMessageBiomeConfigExtensionCMBBOX = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editing TerrainControl.ini");

        cmbboxSettingsMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WriteAll", "WriteWithoutComments", "WriteDisable" }));
        cmbboxSettingsMode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbboxSettingsModeItemStateChanged(evt);
            }
        });
        cmbboxSettingsMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbboxSettingsModeActionPerformed(evt);
            }
        });
        cmbboxSettingsMode.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbboxSettingsModePropertyChange(evt);
            }
        });

        cmbboxLogLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Off", "Quiet", "Standard", "Debug", "Trace" }));
        cmbboxLogLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbboxLogLevelActionPerformed(evt);
            }
        });

        cmbboxBiomeExtension.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".biome", ".bc", ".bc.ini", ".biome.ini" }));

        jLabel1.setText("SettingsMode");

        jLabel2.setText("BiomeConfigExtension");

        jLabel3.setText("LogLevel");

        jButton1.setText("Confirm");

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("SettingsMode will determine how\nconfigs are treated. \n\nYou can select between WriteAll, WriteWithoutComments and WriteDisable.\n\nLogLevel decides how much is logged, and what is shown.\nYou can select between Off, Quiet, Standard, Debug and Trace.\n\n\nBiomeConfigExtension decides what extension will be used for the Biomes\nyou create. You can select between .biome, .bc, .bc.ini and .biome.ini\n(Defaults to .bc)");
        jScrollPane1.setViewportView(jTextArea1);

        lblMessageSettingsModeCMBBOX.setBackground(new java.awt.Color(255, 255, 255));
        lblMessageSettingsModeCMBBOX.setForeground(new java.awt.Color(0, 204, 0));
        lblMessageSettingsModeCMBBOX.setText("jLabel4");
        lblMessageSettingsModeCMBBOX.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblMessageLogLevelCMBBOX.setBackground(new java.awt.Color(255, 255, 255));
        lblMessageLogLevelCMBBOX.setForeground(new java.awt.Color(0, 204, 0));
        lblMessageLogLevelCMBBOX.setText("jLabel4");
        lblMessageLogLevelCMBBOX.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblMessageBiomeConfigExtensionCMBBOX.setBackground(new java.awt.Color(255, 255, 255));
        lblMessageBiomeConfigExtensionCMBBOX.setForeground(new java.awt.Color(0, 204, 0));
        lblMessageBiomeConfigExtensionCMBBOX.setText("jLabel4");
        lblMessageBiomeConfigExtensionCMBBOX.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMessageBiomeConfigExtensionCMBBOX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbboxLogLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbboxSettingsMode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMessageSettingsModeCMBBOX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMessageLogLevelCMBBOX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbboxBiomeExtension, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbboxSettingsMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMessageSettingsModeCMBBOX)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbboxLogLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(lblMessageLogLevelCMBBOX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbboxBiomeExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(lblMessageBiomeConfigExtensionCMBBOX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbboxLogLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbboxLogLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbboxLogLevelActionPerformed

    private void cmbboxSettingsModeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbboxSettingsModeItemStateChanged
        
    }//GEN-LAST:event_cmbboxSettingsModeItemStateChanged

    private void cmbboxSettingsModePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbboxSettingsModePropertyChange
       
    }//GEN-LAST:event_cmbboxSettingsModePropertyChange

    private void cmbboxSettingsModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbboxSettingsModeActionPerformed
        lblMessageSettingsModeCMBBOX.repaint();
        if (cmbboxSettingsMode.getSelectedItem() == "WriteAll") {
            
            lblMessageSettingsModeCMBBOX.setText("'WriteAll' is selected, will write to the config files + add help comments.");
            lblMessageSettingsModeCMBBOX.repaint();
        } else if(cmbboxSettingsMode.getSelectedItem() == "WriteWithoutComments") {
            
            lblMessageSettingsModeCMBBOX.setText("'WriteWithoutComments' is selected, will write to the config files, no help comments.");
            lblMessageSettingsModeCMBBOX.repaint();
        } else if(cmbboxSettingsMode.getSelectedItem() == "WriteDisable") {
            
            lblMessageSettingsModeCMBBOX.setText("'WriteDisable' is selected, will only read from the config files, will not write to them!");
            lblMessageSettingsModeCMBBOX.repaint();
        }
        lblMessageSettingsModeCMBBOX.repaint();
    }//GEN-LAST:event_cmbboxSettingsModeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(terraincontrol_ini_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(terraincontrol_ini_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(terraincontrol_ini_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(terraincontrol_ini_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new terraincontrol_ini_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbboxBiomeExtension;
    private javax.swing.JComboBox<String> cmbboxLogLevel;
    private javax.swing.JComboBox<String> cmbboxSettingsMode;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblMessageBiomeConfigExtensionCMBBOX;
    private javax.swing.JLabel lblMessageLogLevelCMBBOX;
    private javax.swing.JLabel lblMessageSettingsModeCMBBOX;
    // End of variables declaration//GEN-END:variables
}
